### ISSUE TITLE
Tesseract 4?

### ISSUE THREAD

**Issue by makmanalp** [mcs07/conda-recipes#1]
Hi! This feedstock had the honor of being the only one providing a tesseract 4 conda package, and I noticed recently that they disappeared - is there any interest in maintaining those? Otherwise, could I fork this repository and revert back to that version to start building my own?

**Comment by mcs07** [comment]
I had to revert to 3.05 due to problems I was having with incorrect symbol bounding boxes being returned. I'm now trying out upgrading to v4.1.0rc1 to see if it is fixed.

conda-forge now has v4.0.0 (https://github.com/conda-forge/tesseract-feedstock/pull/11) so it's probably best to just use that (although it looks like there is no Windows build).
